controller_joint_names: ['', 'fron_left_steering_joint', 'ffl_wheel_joint', 'front_right_steering_joint', 'ffr_wheel_joint', 'rear_left_steering_joint', 'rfl_wheel_joint', 'rear_right_steering_joint', 'rfr_wheel_joint', ]
