aubo_i5:
  arm_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - shoulder_joint
      - upperArm_joint
      - foreArm_joint
      - wrist1_joint
      - wrist2_joint
      - wrist3_joint

    gains:
      shoulder_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      upperArm_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      foreArm_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      wrist1_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      wrist2_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      wrist3_joint:   {p: 1000.0, i: 0.0, d: 0.1, i_clamp: 0.0}



  gripper_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - finger_joint
    gains:
      finger_joint:  {p: 50.0, d: 1.0, i: 0.01, i_clamp: 1.0}

